'use strict';

const { STICKY_COMMENT_MARKER } = require('./github');

const PRIORITY_ORDER = ['Critical', 'High', 'Medium', 'Low'];
const MAX_LISTED_REQUIREMENTS = 30;
const MAX_LISTED_THREATS = 20;

function priorityRank(priority) {
  const rank = PRIORITY_ORDER.indexOf(priority);
  return rank === -1 ? PRIORITY_ORDER.length : rank;
}

// ThreatCategory serializes through a custom converter — tolerate both a plain
// string and an object shape.
function asDisplayString(value) {
  if (value == null) {
    return '';
  }

  if (typeof value === 'string') {
    return value;
  }

  return value.name ?? value.category ?? String(value);
}

function renderRequirements(requirements) {
  if (requirements.length === 0) {
    return '';
  }

  const sorted = [...requirements].sort(
    (left, right) => priorityRank(left.priority) - priorityRank(right.priority),
  );
  const listed = sorted.slice(0, MAX_LISTED_REQUIREMENTS);

  const items = listed.map((requirement) => {
    const framework = [requirement.frameworkName, requirement.requirementIdNumber]
      .filter(Boolean)
      .join(' ');
    const heading = `- ${requirement.priority ? `**[${requirement.priority}]**` : ''} ${requirement.tailoredRequirement}${framework ? ` _(${framework})_` : ''}`;

    if (!requirement.tailoredDescription) {
      return heading;
    }

    return `${heading}\n  <details><summary>Details</summary>\n\n  ${requirement.tailoredDescription}\n  </details>`;
  });

  const truncationNote =
    sorted.length > listed.length
      ? `\n\n_…and ${sorted.length - listed.length} more requirements. See the full list in Clover._`
      : '';

  return `\n### Security requirements (${requirements.length})\n\n${items.join('\n')}${truncationNote}\n`;
}

function renderThreats(threats) {
  if (threats.length === 0) {
    return '';
  }

  const sorted = [...threats].sort(
    (left, right) => priorityRank(left.severity) - priorityRank(right.severity),
  );
  const listed = sorted.slice(0, MAX_LISTED_THREATS);

  const rows = listed.map((threat) => {
    const cells = [
      threat.severity ?? '',
      threat.threat ?? '',
      asDisplayString(threat.category),
    ].map((cell) => String(cell).replace(/\|/g, '\\|').replace(/\r?\n/g, ' '));

    return `| ${cells.join(' | ')} |`;
  });

  const truncationNote =
    sorted.length > listed.length
      ? `\n\n_…and ${sorted.length - listed.length} more threats._`
      : '';

  return `\n### Threats (${threats.length})\n\n| Severity | Threat | Category |\n|---|---|---|\n${rows.join('\n')}${truncationNote}\n`;
}

function renderReviewComment({ requirements, summary, threats }) {
  const summaryText = summary.summary ?? summary.shortSummary;

  const sections = [
    STICKY_COMMENT_MARKER,
    '## 🛡️ Clover Security Review',
    '',
  ];

  if (summaryText) {
    sections.push(summaryText, '');
  }

  const requirementsSection = renderRequirements(requirements);
  const threatsSection = renderThreats(threats);

  if (!summaryText && !requirementsSection && !threatsSection) {
    sections.push(
      '_The review completed without findings — the pull request may not contain analyzable design content._',
      '',
    );
  } else {
    sections.push(requirementsSection, threatsSection);
  }

  sections.push('---', '_Generated by the [Clover Security Review](https://github.com/clover-security-public/security-review-action) action._');

  return sections.filter((section) => section !== null).join('\n').replace(/\n{3,}/g, '\n\n');
}

function renderTimeoutComment() {
  return [
    STICKY_COMMENT_MARKER,
    '## 🛡️ Clover Security Review',
    '',
    '_The security review is taking longer than expected. Results will appear on the next run of this workflow._',
  ].join('\n');
}

module.exports = { renderReviewComment, renderTimeoutComment };
